### ISSUE TITLE
ModuleNotFound None

### ISSUE THREAD

**Issue by smontanaro** [R9295/panoptisch#1]
I understand output like

```
{
    "reason": "ModuleNotFoundError",
    "name": "winreg"
 },
```

(I'm on Mac, so ``winreg`` won't be found. I don't understand this, however.

```
{
    "reason": "ModuleNotFoundError",
    "name": "None"
 },
```

It's not obvious to me why it should fail to find a module and not know its name. Is it finding calls to ``__import__()`` where it can't evaluate the module name?

**Comment by R9295** [comment]
Hey @smontanaro 
Thanks for reporting this.

It seems that ``ast.ImportFrom`` has no module property when using a relative import, for example:
``from . import x``

https://github.com/R9295/panoptisch/commit/ec8970b429cc85c9dd7e8392295883f9af4531e6
This commit should fix the issue, could you please confirm?

**Comment by R9295** [comment]
Also, as a side note, ``__import__`` statements aren't supported yet, but that's next on the TODO list

**Comment by smontanaro** [comment]
Confirmed, it appears to fix the problem.

**Comment by R9295** [comment]
Great, thank you!
